"""Builds lib/src/mrz_scanner/ocrb_templates.dart, the glyph prototypes the recognizer
matches cells against.

Each prototype is the mean of many renders of one character of OCR-B, the
MRZ font, between random neighbours, at several stroke weights, blurs,
slants and offsets: the cells a camera gives, sampled the way the
recognizer samples them.

The font is Matthew Skala's OCR-B, public domain, packaged by Debian and
Ubuntu as fonts-ocr-b:

    python3 tool/mrz/make_ocrb_templates.py /usr/share/fonts/opentype/ocr-b/OCRB.otf
"""

import base64
import random
import sys

import numpy as np
from PIL import Image, ImageFilter

import ocrb

EM = 96
SAMPLES = 160


def augmented(face, char, rng):
    left = rng.choice(ocrb.ALPHABET)
    right = rng.choice(ocrb.ALPHABET)
    weight = rng.choice([-2, -1, 0, 0, 1, 2, 3])
    image, (bx, by), advance = ocrb.render_line(face, left + char + right, EM,
                                                weight=weight)
    angle = rng.uniform(-2.0, 2.0)
    centre = (bx + advance, by)
    image = image.rotate(angle, resample=Image.BILINEAR, center=centre,
                         fillcolor=255)
    blur = rng.uniform(0, 2.5)
    if blur > 0.2:
        image = image.filter(ImageFilter.GaussianBlur(blur))
    table = ocrb.integral(np.asarray(image))
    height = EM * ocrb.HEIGHT_EM * rng.uniform(0.94, 1.06)
    pitch = advance * rng.uniform(0.96, 1.04)
    dx = rng.uniform(-0.05, 0.05) * pitch
    dy = rng.uniform(-0.04, 0.04) * height
    # PIL turns counter-clockwise for a positive angle, y pointing down.
    return ocrb.sample_cell(table, centre[0] + dx, centre[1] + dy, pitch,
                            height, angle=-np.radians(angle))


def prototypes(font_path, seed=1):
    rng = random.Random(seed)
    face = ocrb.font(font_path, EM)
    result = {}
    for char in ocrb.ALPHABET:
        total = np.zeros(ocrb.GRID_WIDTH * ocrb.GRID_HEIGHT)
        for _ in range(SAMPLES):
            v = ocrb.normalise(augmented(face, char, rng))
            total += v
        result[char] = total / np.linalg.norm(total)
    return result


def quantise(vector):
    # Signed bytes over the largest magnitude: plenty for a correlation.
    scale = 127 / np.abs(vector).max()
    return np.round(vector * scale).astype(np.int8)


def dart(result):
    out = [
        '// GENERATED by tool/mrz/make_ocrb_templates.py from the OCR-B font.',
        '// Do not edit: run the tool again.',
        '',
        "import 'dart:convert';",
        "import 'dart:typed_data';",
        '',
        '/// The characters of [ocrbTemplates], in order.',
        "const String ocrbAlphabet = '%s';" % ocrb.ALPHABET,
        '',
        '/// The width of a template, in samples.',
        'const int templateWidth = %d;' % ocrb.GRID_WIDTH,
        '',
        '/// The height of a template, in samples.',
        'const int templateHeight = %d;' % ocrb.GRID_HEIGHT,
        '',
        '/// How far above the baseline a cell starts, in character heights.',
        'const double cellAbove = %r;' % ocrb.ABOVE,
        '',
        '/// How far below the baseline a cell ends, in character heights.',
        'const double cellBelow = %r;' % ocrb.BELOW,
        '',
        '/// One prototype per character of [ocrbAlphabet], row by row, ink',
        '/// positive, as signed bytes.',
        'final List<Int8List> ocrbTemplates = [',
    ]
    for char in ocrb.ALPHABET:
        data = base64.b64encode(quantise(result[char]).tobytes()).decode()
        out.append("  // %s" % char)
        out.append("  _decode('%s')," % data)
    out += [
        '];',
        '',
        'Int8List _decode(String data) =>',
        '    Int8List.sublistView(base64Decode(data));',
        '',
    ]
    return '\n'.join(out)


if __name__ == '__main__':
    path = sys.argv[1] if len(sys.argv) > 1 else \
        '/usr/share/fonts/opentype/ocr-b/OCRB.otf'
    with open('lib/src/mrz_scanner/ocrb_templates.dart', 'w') as f:
        f.write(dart(prototypes(path)))
