"""Trains the glyph classifier on the cells of tool/mrz/export_cells.dart and
writes lib/src/mrz_scanner/glyph_model.dart.

    python3 tool/mrz/train_glyph_model.py cells.bin [validation.bin]

A small network, numpy alone: the window of a cell and its correlations
with the templates in, one score per character out. Its weights are kept
as signed bytes, one scale per neuron.
"""

import base64
import sys

import numpy as np

ALPHABET = '0123456789<ABCDEFGHIJKLMNOPQRSTUVWXYZ'
WINDOW = 16 * 24
CLASSES = len(ALPHABET)
INPUTS = WINDOW + CLASSES
HIDDEN = 96
# The correlations weigh like a whole window: a unit vector of 384 samples
# has entries near 0.05.
CORRELATION_SCALE = 0.25


def load(path):
    raw = np.fromfile(path, dtype=np.uint8)
    record = 1 + INPUTS * 4
    raw = raw[: len(raw) // record * record].reshape(-1, record)
    labels = raw[:, 0].astype(np.int64)
    features = raw[:, 1:].copy().view('<f4').astype(np.float32)
    features[:, WINDOW:] *= CORRELATION_SCALE
    return features, labels


def init(rng):
    return {
        'w1': rng.normal(0, np.sqrt(2 / INPUTS), (INPUTS, HIDDEN)).astype(np.float32),
        'b1': np.zeros(HIDDEN, np.float32),
        'w2': rng.normal(0, np.sqrt(2 / HIDDEN), (HIDDEN, CLASSES)).astype(np.float32),
        'b2': np.zeros(CLASSES, np.float32),
    }


def forward(p, x):
    h = np.maximum(x @ p['w1'] + p['b1'], 0)
    return h, h @ p['w2'] + p['b2']


def train(x, y, epochs=30, seed=1):
    rng = np.random.default_rng(seed)
    p = init(rng)
    m = {k: np.zeros_like(v) for k, v in p.items()}
    v = {k: np.zeros_like(v) for k, v in p.items()}
    # Every character weighs the same, however rare.
    counts = np.bincount(y, minlength=CLASSES).astype(np.float32)
    weights = (counts.sum() / (CLASSES * np.maximum(counts, 1))) ** 0.5
    step = 0
    batch = 256
    for epoch in range(epochs):
        lr = 2e-3 * (0.5 ** (epoch // 8))
        order = rng.permutation(len(x))
        for start in range(0, len(x), batch):
            idx = order[start:start + batch]
            xb, yb = x[idx], y[idx]
            # Noise on the inputs: the next camera is never quite this one.
            xb = xb + rng.normal(0, 0.01, xb.shape).astype(np.float32)
            h, logits = forward(p, xb)
            logits -= logits.max(1, keepdims=True)
            prob = np.exp(logits)
            prob /= prob.sum(1, keepdims=True)
            wb = weights[yb][:, None]
            grad = prob.copy()
            grad[np.arange(len(yb)), yb] -= 1
            grad *= wb / len(yb)
            g = {
                'w2': h.T @ grad,
                'b2': grad.sum(0),
            }
            dh = grad @ p['w2'].T
            dh[h <= 0] = 0
            g['w1'] = xb.T @ dh + 1e-4 * p['w1']
            g['b1'] = dh.sum(0)
            step += 1
            for k in p:
                m[k] = 0.9 * m[k] + 0.1 * g[k]
                v[k] = 0.999 * v[k] + 0.001 * g[k] ** 2
                mh = m[k] / (1 - 0.9 ** step)
                vh = v[k] / (1 - 0.999 ** step)
                p[k] -= lr * mh / (np.sqrt(vh) + 1e-8)
        _, logits = forward(p, x[:20000])
        acc = (logits.argmax(1) == y[:20000]).mean()
        print('epoch %d accuracy %.4f' % (epoch, acc), flush=True)
    return p


def quantise(w):
    # One scale per output neuron: per column.
    scale = np.abs(w).max(0) / 127
    scale[scale == 0] = 1
    q = np.round(w / scale).astype(np.int8)
    return q, scale.astype(np.float32)


def dequantised(p):
    out = dict(p)
    for k in ('w1', 'w2'):
        q, s = quantise(p[k])
        out[k] = q.astype(np.float32) * s
    return out


def report(p, x, y, name):
    _, logits = forward(p, x)
    guess = logits.argmax(1)
    print('%s accuracy %.4f' % (name, (guess == y).mean()))
    confusions = {}
    for a, b in zip(y[guess != y], guess[guess != y]):
        key = ALPHABET[a] + '>' + ALPHABET[b]
        confusions[key] = confusions.get(key, 0) + 1
    print(sorted(confusions.items(), key=lambda kv: -kv[1])[:15])


def b64(array):
    return base64.b64encode(np.ascontiguousarray(array).tobytes()).decode()


def chunks(text, width=72):
    return [text[i:i + width] for i in range(0, len(text), width)]


def dart(p):
    lines = [
        '// GENERATED by tool/mrz/train_glyph_model.py from cells of synthetic',
        '// documents. Do not edit: train again.',
        '',
        "import 'dart:convert';",
        "import 'dart:typed_data';",
        '',
        '/// The neurons of the hidden layer.',
        'const int modelHidden = %d;' % HIDDEN,
        '',
        '/// The weight of the correlations against the window.',
        'const double modelCorrelationScale = %r;' % CORRELATION_SCALE,
    ]
    for k in ('w1', 'w2'):
        q, s = quantise(p[k])
        # Stored neuron by neuron: the weights of one output together.
        lines += [
            '',
            '/// The weights of layer %s, neuron by neuron, as signed bytes.' % k[1],
            'final Int8List model%sWeights = _bytes(' % k.upper(),
        ]
        lines += ["  '%s'" % c for c in chunks(b64(q.T))]
        lines += [');', '', '/// The scale of each neuron of layer %s.' % k[1],
                  'final Float32List model%sScales = _floats(' % k.upper()]
        lines += ["  '%s'" % c for c in chunks(b64(s.astype('<f4')))]
        lines += [');']
    for k in ('b1', 'b2'):
        lines += ['', '/// The biases of layer %s.' % k[1],
                  'final Float32List model%s = _floats(' % k.upper()]
        lines += ["  '%s'" % c for c in chunks(b64(p[k].astype('<f4')))]
        lines += [');']
    lines += [
        '',
        'Int8List _bytes(String data) => Int8List.sublistView(base64Decode(data));',
        '',
        'Float32List _floats(String data) =>',
        '    Float32List.sublistView(Uint8List.fromList(base64Decode(data)));',
        '',
    ]
    return '\n'.join(lines)


def main():
    x, y = load(sys.argv[1])
    print('%d cells' % len(x), np.bincount(y, minlength=CLASSES))
    p = train(x, y)
    q = dequantised(p)
    report(q, x, y, 'training')
    if len(sys.argv) > 2:
        xv, yv = load(sys.argv[2])
        report(q, xv, yv, 'validation')
    with open('lib/src/mrz_scanner/glyph_model.dart', 'w') as f:
        f.write(dart(p))


if __name__ == '__main__':
    main()
